## 1. Tools needed for Linux/Unix module

- `Plink` 
- `vcftools`
- `BCFtools` 
- `Bedtools`

::: {.callout-tip title="Tools installation" collapse="true"}

1. Open the *terminal* from your `macOS` or `windows WSL` PC (see *pre-course* tutorial if you can't open terminal)

2. Make directory & download software files in there
```bash
cd --                   # to change location to your home

mkdir -p ~/tools/plink  # make a new directories

cd ~/tools/plink        # move to new directories


wget https://s3.amazonaws.com/plink1-assets/plink_linux_x86_64_20250819.zip  # get the plink with wget command
```

3. unzip files
```bash
unzip plink_linux_x86_64_20250819.zip
```
4. change permission
```bash
ll                # to see the lists or contents
chmod +x plink    # permission is changes for execution with +x
ll
```
5. activate plink
```bash
echo 'export PATH=$PATH:~/tools/plink' >> ~/.bashrc  # activate bash

source ~/.bashrc

```
this command ensures you can run it from anywhere in the terminal just by typing plink, without needing to specify the full path

6. check plink activation
```bash
plink --version   # it will print version no.

# or 

plink             # it will print a breif & all options
```
7. Install vcftools, bcftools, bedtools
first see them if tools are installed already or not
```bash
vcftools --version
bcftools --version
bedtools --version
```
If you see *error* or there is no tools like that, then follow the rest of the commands and execute one by one. It will install tools.

```bash
sudo apt install vcftools  # install vcftools at your windows wsl or mac

vcftools --version
```

```bash
sudo apt install bcftools

bcftools --version
```

```bash
sudo apt install bedtools # install vcftools at your windows wsl or mac

bedtools --version
```

:::

## 2. Topics 

0. Setup: Installation
1. Introducing the Shell: What & Why shell? CLI vs GUI
2. Navigating Files and Directories
3. Working With Files and Directories
4. Arguments, Pipes (extra)
6. Shell Scripts (extra)
7. Finding Things (extra)

## 3. Tasks 

- open the terminal or wsl command line
- where am I (print working directory)
- create a directory (folder)
- change working directory to the new directory
- absolute/relative paths of that directory
- list view (different styles)
- arguments
- download tools
- unzip or extract
- copy and paste
- move
- rename
- delete files or folders
